output-format: text

strictness: medium
test-warnings: true
doc-warnings: false
member-warnings: true

ignore-patterns:
  - ^tests?/?
  - /tests?(/|$)
  - (^|/)test_[_a-zA-Z0-9]+.py$
  - (^|/)[_a-zA-Z0-9]+_tests?.py$
  - (^|/)tests?.py

uses:
  - django

pycodestyle:
  full: true
  disable:
    - D100
    - D101
    - D102
    - D103
    - D105
    - D205
    - D400
    - N802  # function name should be lowercase, breaks on tests
    - N806  # variable in function should be lowercase (we are using `CACHE_PREFIX_KEY`)
  options:
    max-line-length: 120

pyflakes:
  disable:
    - F999

pylint:
  disable:
    - too-few-public-methods
    - invalid-name
    - no-self-use
    - no-member
  options:
    max-line-length: 120

dodgy:
  run: true

pydocstyle:
  run: true
  disable:
    - D100  # Missing docstring in public module
    - D101  # Missing docstring in public class
    - D104  # Missing docstring in public package
    - D105  # Missing docstring in magic method
    - D106  # Missing docstring in public nested class (Usually that's for Meta classes)
    - D203  # No blank lines allowed after function docstring
    - D212  # Multi-line docstring summary should start at the first line

    # pydocstyle
    - D400  # First line should end with a period (not 'm') (D415 should be enabled!)
    - D406  # Section name should end with a newline ('Examples', not 'Examples::')
    - D407  # Missing dashed underline after section ('Examples')
    - D412  # No blank lines allowed between a section header and its content ('Examples')
    - N806  # variable in function should be lowercase (we are using `CACHE_PREFIX_KEY`)