# Generated by Django 5.2 on 2025-05-05 14:00

import django.db.models.deletion
import manti_by.apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genres",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="post_to_genre_tags", to="core.tag"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created, UTC")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated, UTC")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("name", models.CharField(max_length=255)),
                ("name_by", models.CharField(max_length=255, null=True)),
                ("meta", models.TextField()),
                ("meta_by", models.TextField(null=True)),
                ("summary", models.TextField()),
                ("summary_by", models.TextField(null=True)),
                ("description", models.TextField()),
                ("description_by", models.TextField(null=True)),
                ("description_en", models.TextField(null=True)),
                (
                    "release",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=manti_by.apps.core.utils.release_path,
                        verbose_name="Release File",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=manti_by.apps.core.utils.cover_path,
                        verbose_name="Cover Image",
                    ),
                ),
                ("is_music", models.BooleanField(blank=True, default=False)),
                ("catnum", models.CharField(blank=True, max_length=16)),
                ("quality", models.CharField(blank=True, max_length=255)),
                ("length", models.CharField(blank=True, max_length=16)),
                ("tracklist", models.TextField(blank=True)),
                ("viewed", models.IntegerField(blank=True, default=0)),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True,
                        related_name="post_genres",
                        through="blog.Genres",
                        to="core.tag",
                        verbose_name="Genre",
                    ),
                ),
                ("related", models.ManyToManyField(blank=True, to="blog.post")),
            ],
            options={
                "verbose_name": "post",
                "verbose_name_plural": "posts",
            },
        ),
        migrations.AddField(
            model_name="genres",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="post_to_genre_posts", to="blog.post"
            ),
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="post_to_tag_posts", to="blog.post"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="post_to_tag_tags", to="core.tag"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="post_tags", through="blog.Tags", to="core.tag", verbose_name="Tags"
            ),
        ),
    ]
