# Generated by Django 1.10.7 on 2017-04-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("blog", "0002_post_converted")]

    operations = [
        migrations.RemoveField(model_name="post", name="converted"),
        migrations.AddField(
            model_name="post",
            name="mp3_preview_ready",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="ogg_preview_ready",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="ogg_release_ready",
            field=models.BooleanField(default=False),
        ),
    ]
