# Generated by Django 3.2.7 on 2021-09-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0015_auto_20201206_2129"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genresproxy",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="tagsproxy",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
