# Generated by Django 4.1.4 on 2023-02-14 11:06

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_alter_post_options_remove_post_original_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "post", "verbose_name_plural": "posts"},
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default=datetime.datetime(2023, 2, 14, 11, 6, 20, 315432, tzinfo=datetime.timezone.utc),
                unique=True,
                verbose_name="Slug",
            ),
            preserve_default=False,
        ),
    ]
