# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created, UTC'),
        ),
    ]
