# Generated by Django 1.10.7 on 2017-04-18 12:19

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone

from manti_by.apps.core.utils import (
    original_name,
    thumb_name,
    preview_name,
    gallery_name,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [("auth", "0008_alter_user_username_max_length")]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created, UTC"
                    ),
                ),
                (
                    "original",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=original_name,
                        verbose_name="Image",
                    ),
                ),
                (
                    "thumb",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=thumb_name,
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=preview_name,
                        verbose_name="Preview Image",
                    ),
                ),
                (
                    "gallery",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=gallery_name,
                        verbose_name="Gallery Image",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
