# Generated by Django 4.0.1 on 2022-01-31 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_auto_20180619_1106"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
    ]
