# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20170502_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='gallery_ready',
        ),
        migrations.RemoveField(
            model_name='image',
            name='preview_ready',
        ),
        migrations.RemoveField(
            model_name='image',
            name='thumbnail_ready',
        ),
    ]
