"""
Django settings for manti.by project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parent.parent

BASE_DIR = PROJECT_DIR.parent

SECRET_KEY = ""  # nosec

DEBUG = False

TEMPLATE_DEBUG = False

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "sorl.thumbnail",
    "manti_by.apps.api",
    "manti_by.apps.blog",
    "manti_by.apps.core",
    "manti_by.apps.gallery",
]

MIDDLEWARE = [
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "django.middleware.http.ConditionalGetMiddleware",
    "manti_by.apps.core.middleware.language.LocaleMiddleware",
]

ROOT_URLCONF = "manti_by.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [PROJECT_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "manti_by.apps.core.context.template_vars",
            ],
            "debug": False,
        },
    }
]

WSGI_APPLICATION = "manti_by.wsgi.application"

BASE_URL = "https://manti.by"

SESSION_COOKIE_DOMAIN = ".manti.by"

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_NAME", "manti_by"),
        "USER": os.environ.get("POSTGRES_USER", "manti_by"),
        "PASSWORD": os.environ.get("POSTGRES_PASS", "manti_by"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", 5432),
    }
}

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

# Cache backend
# https://docs.djangoproject.com/en/1.10/topics/cache/
REDIS_HOST = os.environ.get("REDIS_HOST", "localhost")
REDIS_PORT = os.environ.get("REDIS_PORT", 6379)

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}",
    }
}


# Sorl thumbnailer settings

THUMBNAIL_KVSTORE = "sorl.thumbnail.kvstores.redis_kvstore.KVStore"
THUMBNAIL_REDIS_HOST = REDIS_HOST
THUMBNAIL_REDIS_PORT = REDIS_PORT
THUMBNAIL_QUALITY = 85


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/


def _(x):
    return x


LANGUAGE_CODE = "by"

LANGUAGES = (
    ("by", _("Belarus")),
    ("en", _("English")),
)

LOCALE_PATHS = (PROJECT_DIR / "apps" / "core" / "locale",)
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

LOCALE_URLS = {"by": "manti.by", "en": "en.manti.by"}

DATE_FORMAT = "d E Y"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
]

STATICFILES_DIRS = (PROJECT_DIR / "static",)

STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"

MEDIA_ROOT = BASE_DIR / "content"
MEDIA_URL = "/content/"

FILE_UPLOAD_PERMISSIONS = 0o644


# Email settings

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "localhost"
EMAIL_PORT = 25

DEFAULT_FROM_EMAIL = "admin@manti.by"
DEFAULT_TO_EMAIL = ""


# Meta tags info

META_TITLE = _("Welcome to blog of Alex Chaika.")
META_DESCRIPTION = _("Blog of Alex Chaika. My music, photos and info about me.")
