"""
Django settings for manti.by project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os


PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SECRET_KEY = ""

DEBUG = False

TEMPLATE_DEBUG = False

COMPRESS_ENABLED = True

SITE_ID = 1

ENVIRONMENT = "prod"


# Application definition

INSTALLED_APPS = [
    "manti_by.api",
    "manti_by.apps.blog",
    "manti_by.apps.core",
    "manti_by.apps.gallery",
    "manti_by.apps.profiles",
    "manti_by.apps.shortener",
    "taggit",
    "sorl.thumbnail",
    "compressor",
    "modeltranslation",
    "django_rq",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "django.contrib.sites",
]

MIDDLEWARE = [
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "django.middleware.http.ConditionalGetMiddleware",
    "manti_by.apps.core.middleware.language.LocaleMiddleware",
]

ROOT_URLCONF = "manti_by.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(PROJECT_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "manti_by.apps.core.context_processors.common.global_template_vars",
            ],
            "debug": False,
        },
    }
]

WSGI_APPLICATION = "manti_by.wsgi.application"

BASE_URL = "https://manti.by"

SESSION_COOKIE_DOMAIN = ".manti.by"

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_NAME", "manti_by"),
        "USER": os.environ.get("POSTGRES_USER", "manti_by"),
        "PASSWORD": os.environ.get("POSTGRES_PASS", "manti_by"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", 5432),
    }
}

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

# Cache backend
# https://docs.djangoproject.com/en/1.10/topics/cache/

CACHES = {
    "default": {
        "BACKEND": "redis_cache.cache.RedisCache",
        "LOCATION": f"{os.environ.get('REDIS_HOST', 'localhost')}:{os.environ.get('REDIS_PORT', 6379)}",
        "OPTIONS": {"MAX_ENTRIES": 5000, "DB": 0},
    }
}


# Queues
# https://github.com/rq/django-rq

RQ_QUEUES = {
    "default": {
        "USE_REDIS_CACHE": "default",
    },
}

RQ_ASYNC = True


# Sorl thumbnailer settings

THUMBNAIL_KVSTORE = "sorl.thumbnail.kvstores.redis_kvstore.KVStore"
THUMBNAIL_REDIS_HOST = os.environ.get("REDIS_HOST", "localhost")
THUMBNAIL_REDIS_PORT = os.environ.get("REDIS_PORT", 6379)
THUMBNAIL_QUALITY = 85


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = "be"


def _(x):
    return x


LANGUAGES = (
    ("be", _("Belarussian")),
    ("ru", _("Russian")),
    ("en", _("English")),
)

LOCALE_PATHS = (os.path.join(PROJECT_DIR, "apps", "core", "locale"),)
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True

LOCALE_URLS = {"be": "manti.by", "ru": "ru.manti.by", "en": "en.manti.by"}

DATE_FORMAT = "d E Y"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
]

STATICFILES_DIRS = [os.path.join(PROJECT_DIR, "static")]

STATIC_ROOT = os.path.join(PROJECT_DIR, "static")
STATIC_URL = "/static/"

MEDIA_ROOT = os.path.join(PROJECT_DIR, "content")
MEDIA_URL = "/content/"

FILE_UPLOAD_PERMISSIONS = 0o644


# Email settings

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "localhost"
EMAIL_PORT = 25

DEFAULT_FROM_EMAIL = "admin@manti.by"
DEFAULT_TO_EMAIL = ""


# Allowed hosts

ALLOWED_HOSTS = ["*"]


# Static compressor settings

COMPRESS_OUTPUT_DIR = "cache"
COMPRESS_STORAGE = "compressor.storage.GzipCompressorFileStorage"
COMPRESS_CSS_FILTERS = [
    "compressor.filters.css_default.CssAbsoluteFilter",
    "compressor.filters.cssmin.CSSMinFilter",
]
COMPRESS_CSS_HASHING_METHOD = None


# Meta tags info

META_TITLE = _("Welcome to blog of Alex Chaika.")
META_DESCRIPTION = _("Blog of Alex Chaika. My music, photos and info about me.")
