# Generated by Django 1.10.7 on 2017-04-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blog", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="post",
            name="converted",
            field=models.IntegerField(blank=True, default=0),
        )
    ]
