# Generated by Django 5.2 on 2025-05-05 14:00

import django.db.models.deletion
import manti_by.apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created, UTC")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated, UTC")),
                (
                    "original_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=manti_by.apps.core.utils.images_path, verbose_name="Image"
                    ),
                ),
                ("order", models.IntegerField(blank=True, default=0)),
            ],
            options={
                "verbose_name": "image",
                "verbose_name_plural": "images",
            },
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tags_image_items", to="gallery.image"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tags_tag_items", to="core.tag"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="image",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", through="gallery.Tags", to="core.tag", verbose_name="Tags"
            ),
        ),
    ]
