# Generated by Django 1.10.7 on 2017-04-19 12:34

from django.db import migrations, models
import django.utils.timezone

from manti_by.apps.core.utils import (
    thumb_name,
    preview_name,
    gallery_name,
    original_name,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created, UTC"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, null=True, unique=True, verbose_name="Slug"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.IntegerField(blank=True, default=0)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created, UTC"
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=original_name,
                        verbose_name="Image",
                    ),
                ),
                (
                    "thumbnail_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=thumb_name,
                        verbose_name="Thumbnail Image",
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=preview_name,
                        verbose_name="Preview Image",
                    ),
                ),
                (
                    "gallery_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=gallery_name,
                        verbose_name="Gallery Image",
                    ),
                ),
                ("order", models.IntegerField(blank=True, default=0)),
                (
                    "gallery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="gallery.Gallery",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
