# Generated by Django 1.11.12 on 2018-04-25 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("gallery", "0010_auto_20170721_1155")]

    operations = [migrations.RenameField(model_name="gallery", old_name="name_by", new_name="name_be")]
