# Generated by Django 4.1.4 on 2023-02-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0016_alter_gallery_options_alter_image_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "image", "verbose_name_plural": "images"},
        ),
        migrations.RemoveField(
            model_name="image",
            name="gallery",
        ),
        migrations.RemoveField(
            model_name="image",
            name="phash",
        ),
        migrations.DeleteModel(
            name="Gallery",
        ),
    ]
