# Generated by Django 4.2.1 on 2023-06-12 09:56

from django.db import migrations, models

import manti_by.apps.core.utils


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0017_alter_image_options_remove_image_gallery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="original_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=manti_by.apps.core.utils.image_name, verbose_name="Image"
            ),
        ),
    ]
