# Generated by Django 1.10.7 on 2017-05-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170420_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewed',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
