# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170721_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description_by',
            new_name='description_be',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='meta_by',
            new_name='meta_be',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='name_by',
            new_name='name_be',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='summary_by',
            new_name='summary_be',
        ),
    ]
