# Generated by Django 3.1.4 on 2020-12-06 21:29

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("blog", "0014_auto_20180619_1106"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="genre",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                related_name="post_genres",
                through="blog.GenresProxy",
                to="taggit.Tag",
                verbose_name="Genre",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_music",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="mp3_preview_ready",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="ogg_preview_ready",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="ogg_release_ready",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                related_name="post_tags",
                through="blog.TagsProxy",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
