[package]
name = "manti-io"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = "0.4.10"
json = "0.12.4"
serde_json = "1.0"

[dependencies.rocket_contrib]
version = "0.4.10"
default-features = false
features = ["serve", "tera_templates"]
