# Generated by Django 4.1.4 on 2023-02-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_email_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Email",
        ),
    ]
