name: Django checks

on:
  push:
    branches:
      - master
      - django

jobs:
  checks:

    name: Run Django checks

    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: manti_by.settings.sqlite

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check for missing migrations
        run: |
          python manage.py makemigrations --dry-run --check --verbosity=3

      - name: Run Django system checks
        run: |
          python manage.py check --fail-level WARNING

      - name: Run pre-commit hook
        uses: pre-commit/action@v3.0.0

      - name: Run Pytest suite
        run: |
          pytest --create-db --disable-warnings

      - name: Build docker image
        run: |
          docker build -t mantiby/manti.by:latest .
