# Generated by Django 3.1.7 on 2021-03-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0013_remove_image_phash"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="phash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
